[tool.black]
line-length = 100
target-version = ["py310"]
# Exclude additional directories via regex
extend-exclude = "(env|venv|data|embeddings)/"

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = ["env", "venv", "data", "embeddings"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
]
ignore = [
  "E203",  # whitespace before ':' (black compatibility)
  "E501",  # line too long (allow for prompt text and URLs)
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
