[tool.black]
line-length = 100
target-version = ["py310"]
extend-exclude = [
  "env",
  "venv",
  "data",
  "embeddings",
]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = ["env", "venv", "data", "embeddings"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
]
ignore = [
  "E203",  # whitespace before ':' (black compatibility)
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
