#!/usr/bin/env python3
"""Test unified configuration"""
from unified_config import config

print("=" * 60)
print("UNIFIED CONFIGURATION TEST")
print("=" * 60)
print()
print(f"✅ Configuration loaded from: {config.config_path}")
print()
print("📡 SERVER")
print(f"   Host: {config.HOST}")
print(f"   Port: {config.PORT}")
print(f"   Server IP: {config.SERVER_IP}")
print()
print("🔊 TEXT-TO-SPEECH")
print(f"   Engine: {config.TTS_ENGINE}")
print(f"   Voice: {config.TTS_EDGE_VOICE}")
print()
print("🎤 SPEECH-TO-TEXT")
print(f"   Model: {config.STT_MODEL}")
print(f"   Language: {config.STT_LANGUAGE}")
print()
print("🖥️  GPU")
print(f"   Enabled: {config.USE_GPU}")
print()
print("=" * 60)
print("✅ ALL SETTINGS LOADED SUCCESSFULLY")
print("=" * 60)
